server:
  port: 8080
spring:
  application:
    name: "Clients"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://us-cdbr-east-06.cleardb.net/heroku_89b32b46b59096d"
    username: "bb8d2dd6734b5c"
    password: "e246d8a3"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
